## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending
## on the planner

# The general configuration format for a joint group is as follows:

# <group_name>:
#     planner_configs:
#         - Planner1Config
#         - Planner2Config
#         - ...
#         - PlannerNConfig
#     use_sbpl_collision_checking: [true|false]
#     discretization:
#          joint1_name: discretization resolution
#          joint2_name: discretization resolution
#          ...
#          joint1_name: discretization resolution
#     mprim_filename: string
#         # path to the file describing long and short range motion primitives
#     use_xyz_snap_mprim: bool
#         # whether to use motions computed via interpolating from the current
#         # state to an arm pose computed via 3-dof ik to the goal position
#     use_rpy_snap_mprim: bool
#         # whether to use motions computed via interpolating from the current
#         # state to an arm pose computed via 3-dof ik to the goal orientation
#     use_xyzrpy_snap_mprim: bool
#         # whether to use motions computed via interpolating from the current
#         # state to an arm pose computed via 6-dof ik to the goal pose
#     use_short_dist_mprims: bool
#         # whether to use short distance motion primitives
#     xyz_snap_dist_thresh: double
#     rpy_snap_dist_thresh: double
#     xyzrpy_snap_dist_thresh: double
#         # the distance from the goal at which to start using ik motion
#         # primitives
#     short_dist_mprims_thresh: double
#         # the distance from the goal at which to start using short distance
#         # motion primitves
#     shortcut_path: bool
#         # whether to apply a shortcutter to the discrete path to smooth the
#         # final trajectory
#
# planner_configs:
#     Planner1Config:
#         planner1_param1: value
#         planner2_param1: value
#         ...
#         plannern_param1: value
#     ...

check_torques: true

right_arm:
    ### Available Search Parameters ###
    planner_configs:
        - ARAConfigDefault
        - MHAConfigDefault

    ### Collision Checking Parameters ###
    use_sbpl_collision_checking: true

    ### Graph Parameters ###

    # angular resolution of each active joint variable
    discretization:
        r_shoulder_pan_joint:   0.017453292519943
        r_shoulder_lift_joint:  0.017453292519943
        r_upper_arm_roll_joint: 0.017453292519943
        r_forearm_roll_joint:   0.017453292519943
        r_elbow_flex_joint:     0.017453292519943
        r_wrist_flex_joint:     0.017453292519943
        r_wrist_roll_joint:     0.017453292519943

    ### Action Parameters ###

    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
    shortcut_path: true

right_arm_and_torso:
    planner_configs:
        - ARAConfigDefault
        - MHAConfigDefault
    use_sbpl_collision_checking: true
    discretization:
        torso_lift_joint:       0.02
        r_shoulder_pan_joint:   0.017453292519943
        r_shoulder_lift_joint:  0.017453292519943
        r_upper_arm_roll_joint: 0.017453292519943
        r_forearm_roll_joint:   0.017453292519943
        r_elbow_flex_joint:     0.017453292519943
        r_wrist_flex_joint:     0.017453292519943
        r_wrist_roll_joint:     0.017453292519943
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
    shortcut_path: true

left_arm:
    planner_configs:
        - ARAConfigDefault
        - MHAConfigDefault
    use_sbpl_collision_checking: true
    discretization:
        l_shoulder_pan_joint:   0.017453292519943
        l_shoulder_lift_joint:  0.017453292519943
        l_upper_arm_roll_joint: 0.017453292519943
        l_forearm_roll_joint:   0.017453292519943
        l_elbow_flex_joint:     0.017453292519943
        l_wrist_flex_joint:     0.017453292519943
        l_wrist_roll_joint:     0.017453292519943
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
    shortcut_path: true

left_arm_and_torso:
    planner_configs:
        - ARAConfigDefault
        - MHAConfigDefault
    use_sbpl_collision_checking: true
    discretization:
        torso_lift_joint:       0.02
        l_shoulder_pan_joint:   0.017453292519943
        l_shoulder_lift_joint:  0.017453292519943
        l_upper_arm_roll_joint: 0.017453292519943
        l_forearm_roll_joint:   0.017453292519943
        l_elbow_flex_joint:     0.017453292519943
        l_wrist_flex_joint:     0.017453292519943
        l_wrist_roll_joint:     0.017453292519943
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
    shortcut_path: true

planner_configs:
    ARAConfigDefault:
        type: ARA*
        epsilon: 100.0
        use_bfs_heuristic: true
        bfs_res_x: 0.02
        bfs_res_y: 0.02
        bfs_res_z: 0.02
        bfs_sphere_radius: 0.02
    MHAConfigDefault:
        type: MHA*
        epsilon: 100.0
        mha_epsilon: 2.0
        use_bfs_heuristic: true
        bfs_res_x: 0.02
        bfs_res_y: 0.02
        bfs_res_z: 0.02
        bfs_sphere_radius: 0.02

collision_world:
    size_x: 3.5
    size_y: 3.0
    size_z: 2.0
    origin_x: -1.0
    origin_y: -1.5
    origin_z: 0.0
    res_m: 0.02
    max_distance: 0.2

collision_groups:
  - name: body
    type: voxels
    root_name: base_footprint
    tip_name: head_pan_link
    collision_links:
    - name: head_tilt
      root: head_tilt_link
    - name: head_pan
      root: head_pan_link
#    - name: head_mount
#      root: head_mount_link
#    - name: laser
#      root: laser_tilt_link
    - name: laser_mount
      root: laser_tilt_mount_link
    - name: torso
      root: torso_lift_link
    - name: base
      root: base_link

  - name: left_arm
    type: voxels
    root_name: base_footprint
    tip_name: l_wrist_roll_link
    collision_links:
    - name: shoulder
      root: l_shoulder_pan_link
    - name: upper_arm
      root: l_upper_arm_link
    - name: forearm
      root: l_forearm_link
    - name: gripper
      root: l_gripper_palm_link
    - name: left_finger
      root: l_gripper_l_finger_link
    - name: right_finger
      root: l_gripper_r_finger_link
    - name: right_finger_tip
      root: l_gripper_r_finger_tip_link
    - name: left_finger_tip
      root: l_gripper_l_finger_tip_link

  - name: right_arm
    type: spheres
    root_name: torso_lift_link
    tip_name: r_wrist_roll_link
    collision_links:
    - name: shoulder
      root: r_shoulder_pan_link
      spheres: sh0
    - name: upper_arm
      root: r_upper_arm_roll_link
      spheres: ua0 ua1 ua2 ua3
    - name: forearm
      root: r_forearm_roll_link
      spheres: fa0 fa1 fa2 fa3 fa4 fa5 fa6
    - name: gripper
      root: r_wrist_roll_link
      spheres: gr0 gr1 gr2
    - name: left_finger
      root: r_gripper_l_finger_link
      spheres: lf0 lf1
    - name: right_finger
      root: r_gripper_r_finger_link
      spheres: rf0 rf1
    - name: right_finger_tip
      root: r_gripper_r_finger_tip_link
      spheres: rft0 rft1
    - name: left_finger_tip
      root: r_gripper_l_finger_tip_link
      spheres: lft0 lft1

collision_spheres:

# - { name: sh0, x: 0.09, y: 0.0, z: -0.02, radius: 0.18, priority: 5 }
  - { name: sh0, x: 0.13, y: 0.0, z: -0.04, radius: 0.16, priority: 5 }

  - { name: ua0, x: 0.18,   y: 0.0,     z: -0.015,  radius: 0.11,   priority: 4 }
  - { name: ua1, x: 0.26,   y: 0.00,    z: -0.035,  radius: 0.08,   priority: 4 }
  - { name: ua2, x: 0.3275, y: 0.00,    z: -0.035,  radius: 0.08,   priority: 4 }
  - { name: ua3, x: 0.40,   y: 0.0,     z: -0.0,    radius: 0.105,  priority: 2 }

  - { name: fa0, x: 0.13,   y: 0.0,     z: 0.005,   radius: 0.075,  priority: 2 }
  - { name: fa1, x: 0.20,   y: 0.025,   z: -0.01,   radius: 0.055,  priority: 3 }
  - { name: fa2, x: 0.20,   y: -0.025,  z: -0.01,   radius: 0.055,  priority: 3 }
  - { name: fa3, x: 0.265,  y: 0.0275,  z: -0.015,  radius: 0.05,   priority: 3 }
  - { name: fa4, x: 0.265,  y: -0.0275, z: -0.015,  radius: 0.05,   priority: 3 }
  - { name: fa5, x: 0.32,   y: 0.0225,  z: -0.005,  radius: 0.05,   priority: 3 }
  - { name: fa6, x: 0.32,   y: -0.0225, z: -0.005,  radius: 0.05,   priority: 3 }

  - { name: gr0, x: 0.0725, y: -0.0175, z: 0.00, radius: 0.04, priority: 2 }
  - { name: gr1, x: 0.0725, y: 0.0175,  z: 0.00, radius: 0.04, priority: 2 }
  - { name: gr2, x: 0.0925, y: 0.0,     z: 0.00, radius: 0.04, priority: 2 }

  - { name: lf0, x: 0.03, y: 0.025,     z: 0.00, radius: 0.04,  priority: 1 }
  - { name: lf1, x: 0.08, y: 0.0175,    z: 0.00, radius: 0.035, priority: 1 }

  - { name: rf0, x: 0.03, y: -0.025,    z: 0.00, radius: 0.04,  priority: 1 }
  - { name: rf1, x: 0.08, y: -0.0175,   z: 0.00, radius: 0.035, priority: 1 }

  - { name: rft0, x: 0.015, y: 0.005, z: 0.00, radius: 0.03, priority: 1 }
  - { name: rft1, x: 0.035, y: 0.005, z: 0.00, radius: 0.02, priority: 1 }

  - { name: lft0, x: 0.015, y: -0.005, z: 0.00, radius: 0.03, priority: 1 }
  - { name: lft1, x: 0.035, y: -0.005, z: 0.00, radius: 0.02, priority: 1 }
